### ISSUE TITLE
Add mechanism to manually inject events

### ISSUE THREAD

**Issue by acatangiu** [rust-vmm/event-manager#24]
Seeing how the `EventManager` interface completely hides event handling from the `EventManager` user, it is very difficult to externally/artificially trigger an event for a given `Subscriber`.

A mechanism to manually/artificially inject events for a given `Subscriber` would be useful in the case of restoring from snapshot or live migration where post migration you'd want to artificially kick all devices.

**Comment by andreeaflorescu** [comment]
How is this currently handled in Firecracker?

@alexandruag do you think the `remote_endpoint` can be used for that?

**Comment by acatangiu** [comment]
> How is this currently handled in Firecracker?

It is not.

> do you think the `remote_endpoint` can be used for that?

I don't see how.

What we'd need is a top-level interface that for a given `Subscriber` will generate/inject/simulate a given `EventSet` on either/both:
- all registered `FD`s for that `Subscriber`
- a given registered `FD` for that `Subscriber`

**Comment by alexandruag** [comment]
Apologies for being so late to the discussion :( While the `EventManager` does hide things, events can still be triggered by interacting with event sources outside the `EventManager` (for example, write to some `EventFd` that's associated with a subscriber). Alternatively, subscribers can be prodded through an interface of their own, unrelated to the `EventManager` and `EventSubscriber` abstractions. 

I think adding an event injection interface creates corner cases and adds complexity without really presenting an unique solution to any particular problem, but at the same time I'm happy to chat about specific examples, because I might very well miss some aspects and/or use cases :(

**Comment by acatangiu** [comment]
update: not sure if needed anymore, closing for now. We can reopen if/when we find a clear need for it.
